### ISSUE TITLE
appendTextWithHeader fails at end of document

### ISSUE THREAD

**Issue by siddalp-actual** [siddalp-actual/pythonGooogleDoc#1]
Invalid requests[0].insertText: Index 6321 must be less than the end index of the referenced segment, 6320.
Traceback (most recent call last):
  File "/home/pi/pgm/gkeep/update_note.py", line 553, in <module>
    outGdoc.appendTextWithHeader(today.strftime("Update for %a %d %b %Y"), p)
  File "../googledocs/gdocHelper.py", line 63, in appendTextWithHeader
    self.insertTextWithHeader(header, text, self.docExtent + 1)
  File "../googledocs/gdocHelper.py", line 87, in insertTextWithHeader
    self.docs_service.documents()
  File "/home/pi/.pyenv/versions/py3/lib/python3.9/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/pi/.pyenv/versions/py3/lib/python3.9/site-packages/googleapiclient/http.py", line 915, in execute
    raise HttpError(resp, content, uri=self.uri)

**Comment by siddalp-actual** [comment]
Well, line 63 in gdocHelper.py, routine appendTextWithHeader() will be the problem:
```
self.insertTextWithHeader(header, text, self.docExtent + 1)
```
needs to be changed so that the insertion point is strictly **less** then the end, ie `docExtent - 1`
